services:
  client:
    build: client/
    volumes:
      - ./client/:/app

  app:
    build: server/
    ports:
      - "8000:8000"
    env_file:
      - server/.env
    volumes:
      - ./server/:/app
    depends_on:
      - redis
      - db

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"

  db:
    image: postgres
    env_file:
      - server/.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
