services:
  client:
    build: client/
    volumes:
      - ./client/:/app

  app-base: &app-base
    build: server/
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/app

  app:
    <<: *app-base
    env_file:
      - server/.dev.env
    depends_on:
      - redis
      - db

  app-test:
    <<: *app-base
    env_file:
      - server/.test.env
    depends_on:
      - redis-test

  redis:
    image: redis/redis-stack-server

  redis-test:
    image: redis/redis-stack-server

  db:
    image: postgres
    env_file:
      - server/.dev.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
