services:
  client:
    build: client/
    volumes:
      - ./client/:/app

  app:
    build: server/
    ports:
      - "8000:8000"
    env_file:
      - server/.env
    volumes:
      - ./server/:/app
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
