# Generated by Django 4.1.5 on 2023-02-04 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trivia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="extra_data",
        ),
        migrations.RemoveField(
            model_name="game",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="game",
            name="status",
        ),
        migrations.RemoveField(
            model_name="game",
            name="user",
        ),
        migrations.AlterField(
            model_name="game",
            name="type",
            field=models.IntegerField(choices=[(1, "Ranked"), (2, "Normal"), (3, "Training")]),
        ),
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(1, "Draw"), (2, "Loss"), (3, "Win")]),
                ),
                ("rank", models.PositiveIntegerField()),
                ("extra_data", models.JSONField(null=True)),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trivia.game"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                related_name="games",
                through="trivia.UserGame",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
