# Generated by Django 4.1.5 on 2023-02-04 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trivia", "0002_remove_game_extra_data_remove_game_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergame",
            name="opponent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opponent_user_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usergame",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
